### ISSUE TITLE
If the compiler path includes spaces, such as `C:\Program Files (x86)\...`, the output is incorrect

### ISSUE THREAD

**Issue by roachsinai** [0xabu/MsBuildCompileCommandsJson#2]
The command I used to export compile_commands.json is:

`& "${env:ProgramFiles(x86)}\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\MSBuild.exe" .\YBlaze.sln /p:Configuration=Release /t:Rebuild -logger:F:\code\tools\MsBuildCompileCommandsJson\bin\Release\netstandard2.0\CompileCommandsJson.dll`

And I found there are some entries in json compile database has wrong value of `"file"`:

![image](https://user-images.githubusercontent.com/9500049/161394878-6c7382f3-331d-4119-b392-7e541a544ac5.png)
![image](https://user-images.githubusercontent.com/9500049/161394885-4334a799-6a40-4df1-ba16-e39edec13909.png)
![image](https://user-images.githubusercontent.com/9500049/161394908-08d341d9-ff6e-4dcf-b195-fa6f1382d211.png)
![image](https://user-images.githubusercontent.com/9500049/161394920-ee53b4f9-2e3d-452a-90fa-90c5eb57b404.png)

It look likes it split `Files (x86)\\Microsoft Visual Studio\\2019\\Community\\VC\\Tools\\MSVC\\14.29.30133\\bin\\HostX86\\x64\\CL.exe` to 4 entries.

So did I run wrong command which leads to this? Thanks in advanced!

**Comment by 0xabu** [comment]
This looks like a bug on my part. A workaround would be to install the compiler tools in a path without a space in it (which is the way I've used this code).

**Comment by 0xabu** [comment]
Hmm, I'm actually calling [shell32!CommandLineToArgvW](https://docs.microsoft.com/en-us/windows/win32/api/shellapi/nf-shellapi-commandlinetoargvw) to process the command line, which I would expect to do the right thing. I'm guessing that either msbuild is not quoting the path to CL.exe correctly in the command line, or we're hitting the "special interpretation of backslash characters" mentioned at the end of the above link.

**Comment by roachsinai** [comment]
> This looks like a bug on my part. A workaround would be to install the compiler tools in a path without a space in it (which is the way I've used this code).

Maybe, I've tried create a soft link of msbuild, and get same results.

**Comment by 0xabu** [comment]
Could you show me the "command" portion from one of the erroneous entries in the json DB? It's fine to obfuscate everything after the compiler path.

**Comment by roachsinai** [comment]
> Could you show me the "command" portion from one of the erroneous entries in the json DB? It's fine to obfuscate everything after the compiler path.

Yes,

```
{"directory": "C:\\Users\\xq\\source\\repos\\YBlaze\\YBlaze",
 "command": "C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\VC\\Tools\\MSVC\\14.29.30133\\bin\\HostX86\\x64\\CL.exe /c /IC:\\Users\\xq\\source\\repos\\YBlaze\\packages\\Microsoft.ML.OnnxRuntime.Gpu.1.8.1\\build\\native\\../../build/native/include/ /I\"E:\\vcpkg\\installed\\x64-windows\\include\" /ZI /JMC /nologo /W3 /WX- /diagnostics:column /sdl /Od /D _DEBUG /D _CONSOLE /D _USE_MATH_DEFINES /D _UNICODE /D UNICODE /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /permissive- /Zc:wchar_t /Zc:forScope /Zc:inline /std:c++17 /Fo\"x64\\Debug\\\\\" /Fd\"x64\\Debug\\vc142.pdb\" /external:W3 /Gd /TP /FC /errorReport:queue YBlaze.cpp dt\\yolo5.cpp dt\\dtBase.cpp dt\\Palmdt.cpp l1k\\Handl1k.cpp l1k\\l1kBase.cpp ort\\Ortsshl.cpp utils\\ctRect.cpp utils\\LoadFile.cpp utils\\Padii.cpp utils\\rtii.cpp",
 "file": "Files"},
{"directory": "C:\\Users\\xq\\source\\repos\\YBlaze\\YBlaze",
 "command": "C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\VC\\Tools\\MSVC\\14.29.30133\\bin\\HostX86\\x64\\CL.exe /c /IC:\\Users\\xq\\source\\repos\\YBlaze\\packages\\Microsoft.ML.OnnxRuntime.Gpu.1.8.1\\build\\native\\../../build/native/include/ /I\"E:\\vcpkg\\installed\\x64-windows\\include\" /ZI /JMC /nologo /W3 /WX- /diagnostics:column /sdl /Od /D _DEBUG /D _CONSOLE /D _USE_MATH_DEFINES /D _UNICODE /D UNICODE /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /permissive- /Zc:wchar_t /Zc:forScope /Zc:inline /std:c++17 /Fo\"x64\\Debug\\\\\" /Fd\"x64\\Debug\\vc142.pdb\" /external:W3 /Gd /TP /FC /errorReport:queue YBlaze.cpp dt\\yolo5.cpp dt\\dtBase.cpp dt\\Palmdt.cpp l1k\\Handl1k.cpp l1k\\l1kBase.cpp ort\\Ortsshl.cpp utils\\ctRect.cpp utils\\LoadFile.cpp utils\\Padii.cpp utils\\rtii.cpp",
 "file": "(x86)\\Microsoft"},
{"directory": "C:\\Users\\xq\\source\\repos\\YBlaze\\YBlaze",
 "command": "C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\VC\\Tools\\MSVC\\14.29.30133\\bin\\HostX86\\x64\\CL.exe /c /IC:\\Users\\xq\\source\\repos\\YBlaze\\packages\\Microsoft.ML.OnnxRuntime.Gpu.1.8.1\\build\\native\\../../build/native/include/ /I\"E:\\vcpkg\\installed\\x64-windows\\include\" /ZI /JMC /nologo /W3 /WX- /diagnostics:column /sdl /Od /D _DEBUG /D _CONSOLE /D _USE_MATH_DEFINES /D _UNICODE /D UNICODE /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /permissive- /Zc:wchar_t /Zc:forScope /Zc:inline /std:c++17 /Fo\"x64\\Debug\\\\\" /Fd\"x64\\Debug\\vc142.pdb\" /external:W3 /Gd /TP /FC /errorReport:queue YBlaze.cpp dt\\yolo5.cpp dt\\dtBase.cpp dt\\Palmdt.cpp l1k\\Handl1k.cpp l1k\\l1kBase.cpp ort\\Ortsshl.cpp utils\\ctRect.cpp utils\\LoadFile.cpp utils\\Padii.cpp utils\\rtii.cpp",
 "file": "Visual"},
{"directory": "C:\\Users\\xq\\source\\repos\\YBlaze\\YBlaze",
 "command": "C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\VC\\Tools\\MSVC\\14.29.30133\\bin\\HostX86\\x64\\CL.exe /c /IC:\\Users\\xq\\source\\repos\\YBlaze\\packages\\Microsoft.ML.OnnxRuntime.Gpu.1.8.1\\build\\native\\../../build/native/include/ /I\"E:\\vcpkg\\installed\\x64-windows\\include\" /ZI /JMC /nologo /W3 /WX- /diagnostics:column /sdl /Od /D _DEBUG /D _CONSOLE /D _USE_MATH_DEFINES /D _UNICODE /D UNICODE /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /permissive- /Zc:wchar_t /Zc:forScope /Zc:inline /std:c++17 /Fo\"x64\\Debug\\\\\" /Fd\"x64\\Debug\\vc142.pdb\" /external:W3 /Gd /TP /FC /errorReport:queue YBlaze.cpp dt\\yolo5.cpp dt\\dtBase.cpp dt\\Palmdt.cpp l1k\\Handl1k.cpp l1k\\l1kBase.cpp ort\\Ortsshl.cpp utils\\ctRect.cpp utils\\LoadFile.cpp utils\\Padii.cpp utils\\rtii.cpp",
 "file": "Studio\\2019\\Community\\VC\\Tools\\MSVC\\14.29.30133\\bin\\HostX86\\x64\\CL.exe"},
```

**Comment by 0xabu** [comment]
Please reopen if you still encounter this problem.

**Comment by roachsinai** [comment]
@0xabu disappears, thanks!
