### ISSUE TITLE
cctmp.json: The term 'cctmp.json' is not recognized as a name of a cmdlet

### ISSUE THREAD

**Issue by roachsinai** [0xabu/MsBuildCompileCommandsJson#3]
I read from Readme, support use `;cctmp.json` follow `-logger:F:\code\tools\MsBuildCompileCommandsJson\bin\Release\netstandard2.0\CompileCommandsJson.dll;cctmp.json` to change export json file name, but I got below error:

```
cctmp.json: The term 'cctmp.json' is not recognized as a name of a cmdlet, function, script file, or executable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
```

So, could you please tell me what's wrong with my command?

`
 & "${env:ProgramFiles(x86)}\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\MSBuild.exe" -logger:F:\code\tools\MsBuildCompileCommandsJson\bin\Release\netstandard2.0\CompileCommandsJson.dll;cctmp.json ./YBlaze.sln /t:Rebuild
`

**Comment by 0xabu** [comment]
You'll need to escape the ; character for PowerShell so it is passed to msbuild and not interpreted as a command separator.

**Comment by roachsinai** [comment]
Got it, thanks!
